# Generated by Django 6.0 on 2025-12-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks1',
            new_name='chemistry',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='marks2',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='marks3',
            new_name='physics',
        ),
    ]
